DAO_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helper.urls'))
]

helper/urls.py
from django.urls import path
from .views import DProject, user, schedule, group


app_name = 'helper'
urlpatterns = [
    path('register/', user.register, name='register'),
    path('login/', user.login, name='login'),
    path('', user.index, name='index'),
    path('user/home/', user.home, name='home'),
    path('user/pwd_change/', user.pwd_change, name='pwd_change'),
    path('user/friends_admin/', user.friends_admin, name='friends_admin'),
    path('dproject/home/', DProject.home, name='dproject_homepage'),
    path('dproject/hot/<int:pg>', DProject.hot, name='hot'),
    path('dproject/<int:pk>/modify', DProject.modify, name='dproject_modify'),
    path('dproject/<int:pk>/delete', DProject.delete, name='dproject_delete'),
    path('dproject/add', DProject.add, name='dproject_add'),
    path('dproject/<int:pk>/', DProject.dproject, name='dproject_page'),
    path('dproject/friend/<int:friend_id>/', DProject.public, name='public'),
    path('logout/', user.logout, name='logout'),
    path('group/<int:pid>/', group.group_admin, name='group_admin'),
    path('group/<int:pid>/<int:pk>/', group.home, name='group_home'),
    path('group/<int:pid>/<int:pk>/add_assign/', group.add_assign, name='assign_add'),
    path('group/<int:pid>/<int:pk>/add_sub_assign/', group.add_sub_assign, name='sub_assign_add'),
    path('schedule/', schedule.home, name='schedule_home'),
    path('schedule/add/', schedule.add_todo_list, name='schedule_add'),
    path('schedule/daily', schedule.daily_schedules, name='schedule_daily'),
]

helper/views/DProject.py
from django import forms
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponseNotFound
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from ..models import *
from .settings import *
import datetime
import math


class ModifyForm(forms.Form):
    title = forms.CharField(label='标题', max_length=50,
                            widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    content = forms.CharField(label='项目描述', widget=forms.Textarea(attrs={'class': 'form-control form-control-user mb-5'}))


@login_required
def home(request):
    user = request.user

    dprojects = DProject.objects.filter(user_id__exact=user.id).order_by('-modified_time')
    collections = Collection.objects.filter(user_id__exact=user.id).order_by('-dproject__collect_amount')
    return render(request, '../templates/dproject/home.html',
                  {
                      'dprojects': dprojects,
                      'collections': collections
                  })


@login_required
def dproject(request, pk):
    dproject = get_object_or_404(DProject, pk=pk)
    user: User = request.user
    if user.collection_set.filter(dproject_id__exact=dproject.pk).count() == 0:
        is_collected = False
    else:
        is_collected = True
    comments = dproject.comment_set.all().order_by('created_time')
    if request.method == 'POST':
        delete_comment = request.POST.get('delete_comment')
        create_comment = request.POST.get('create_comment')
        collect_dproject = request.POST.get('collect_dproject')
        if not (delete_comment is None):
            try:
                comment = Comment.objects.filter(user_id__exact=user.id,
                                                 dproject_id__exact=dproject.id,
                                                 content__exact=delete_comment)[0]
                comment.delete()
            except IndexError:
                pass

        if not (collect_dproject is None):
            collection = Collection.objects.filter(user_id__exact=user.id, dproject_id__exact=dproject.id)
            if len(collection) == 0:
                new_collection = Collection(user=user, dproject=dproject)
                dproject.collect_amount += 1
                dproject.save()
                new_collection.save()
                is_collected = True
            else:
                collection.delete()
                is_collected = False

        if not (create_comment is None):
            new_comment = Comment(user=user, dproject=dproject, content=create_comment)
            new_comment.save()
    else:
        dproject.pageview += 1
        dproject.save()

    return render(request, '../templates/dproject/dproject.html',
                  {'dproject': dproject, 'comments': comments, 'user': user, 'is_collected': is_collected})


@login_required
def modify(request, pk):
    dproject = get_object_or_404(DProject, pk=pk)
    if dproject.user != request.user:
        return HttpResponseForbidden

    if request.method == "POST":
        form = ModifyForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            dproject.title = title
            dproject.content = content
            dproject.save()
            return HttpResponseRedirect(reverse('helper:dproject_page', args=(dproject.id,)))
    else:
        form = ModifyForm(initial={'title': dproject.title, 'content': dproject.content})

    return render(request, '../templates/dproject/modify.html', {'form': form})


@login_required
def delete(request, pk):
    dproject = get_object_or_404(DProject, pk=pk)
    if dproject.user != request.user:
        return HttpResponseForbidden
    dproject.delete()
    return HttpResponseRedirect(reverse("helper:dproject_homepage"))


@login_required
def add(request):
    user = request.user

    if request.method == "POST":
        form = ModifyForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            dproject = DProject(user=user, title=title, content=content)
            dproject.save()
            return HttpResponseRedirect(reverse('helper:dproject_page', args=(dproject.id,)))
    else:
        form = ModifyForm()

    return render(request, '../templates/dproject/modify.html', {'form': form})


def hot(request, pg):
    dprojects = DProject.objects.filter(Q(user__dproject__pageview__gte=HOT_BLOG_PAGEVIEW,
                                  modified_time__gte = timezone.now() -
                                                       datetime.timedelta(days=BLOGPAGE_HOT_BLOG_DAY)) |
                                Q(modified_time__gte = timezone.now() -
                                                       datetime.timedelta(days=BLOGPAGE_COMMON_BLOG_DAY))).distinct().order_by('-modified_time')
    page_num = math.ceil(len(dprojects) / BLOGPAGE_BLOG_NUMBER)
    if pg > page_num or pg < 1:
        return HttpResponseNotFound()

    if pg * BLOGPAGE_BLOG_NUMBER > len(dprojects):
        number = len(dprojects)
    else:
        number = pg * BLOGPAGE_BLOG_NUMBER

    dprojects = dprojects[(pg - 1) * BLOGPAGE_BLOG_NUMBER: number]
    return render(request, '../templates/dproject/hot.html',
                  {
                      'dprojects': dprojects,
                      'page_num': page_num,
                      'current_page': pg
                  })


@login_required
def public(request, friend_id):
    user: User = request.user
    friend = Friend.objects.filter(user_id__exact=user.id, friend_id__exact=friend_id)
    if len(friend) == 0 and friend_id != user.id:
        return HttpResponseForbidden()
    dprojects = DProject.objects.filter(user_id__exact=friend_id)
    message = None
    if friend_id == user.id:
        friend_user = user
    else:
        friend_user = friend[0].friend
        if friend[0].authority == 0:
            dprojects = None
            message = "没有权限访问！"

    return render(request, '../templates/dproject/friend.html',
                  {
                      'dprojects': dprojects,
                      'friend': friend_user,
                      'message': message
                  })

helper/views/schedule.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.forms import Form
from django.forms import fields
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from helper import models
import datetime
import copy
from .settings import *


class TodoForm(Form):
    CYCLE_CHOICES = (
        ('N', '不重复'),
        ('D', '每天'),
        ('W', '每周'),
        ('M', '每月')
    )
    REPEAT_CYCLE = (
        (False, '不重复'),
        (True, '重复')
    )
    description = fields.CharField(label='日程描述', required=True, max_length=50,
                                   widget=forms.TextInput(attrs={
                                       'class': 'form-control form-control-user mb-5'
                                   }))
    type = fields.CharField(label='日程类型', required=True, max_length=2,
                            widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    weight = fields.IntegerField(label='权重', required=True, max_value=100,
                                 widget=forms.NumberInput(attrs={'class': 'form-control form-control-user mb-5'}))
    is_repeated = fields.ChoiceField(label='是否重复', choices=REPEAT_CYCLE, widget=forms.RadioSelect)
    repeat_cycle = fields.ChoiceField(label='重复周期', required=False, choices=CYCLE_CHOICES, widget=forms.RadioSelect)
    start_time = fields.DateTimeField(label='开始时间', required=True,
                                      widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    deadline = fields.DateTimeField(label='截止时间', required=True,
                                    widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    expected_minutes_consumed = fields.IntegerField(label='预期花费时间', required=False,
                                                    widget=forms.NumberInput(
                                                        attrs={'class': 'form-control form-control-user mb-5'}))


@login_required
def add_todo_list(request):
    if request.method == "GET":
        form = TodoForm()
        return render(request, "../templates/schedule/add_schedule.html", {'form': form})
    else:
        form = TodoForm(request.POST)
        if form.is_valid():
            user = request.user
            description = form.cleaned_data['description']
            type = form.cleaned_data['type']
            is_repeated = form.cleaned_data['is_repeated']
            repeat_cycle = form.cleaned_data['repeat_cycle']
            if repeat_cycle == 'N':
                repeat_cycle = None
            start_time = form.cleaned_data['start_time']
            weight = form.cleaned_data['weight']
            deadline = form.cleaned_data['deadline']
            emc = form.cleaned_data['expected_minutes_consumed']
            models.Schedule.objects.create(user_id=user.id, description=description, type=type, is_repeated=is_repeated,
                                           is_done=False, start_time=start_time, weight=weight, deadline=deadline,
                                           expected_minutes_consumed=emc, repeat_cycle=repeat_cycle)
            return HttpResponseRedirect(reverse("helper:schedule_home"))
        else:
            message = "添加失败！"
            return render(request, "../templates/schedule/add_schedule.html", {'form': form, 'message': message})


def get_schedules(user, search_day_num):
    schedule_not_repeated = user.schedule_set.filter(is_done__exact=False, is_repeated__exact=False)
    schedule_daily = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='D',
                                              deadline__gte=timezone.now())
    schedule_weekly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='W',
                                               deadline__gte=timezone.now())
    schedule_monthly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='M',
                                                deadline__gte=timezone.now())

    def update_time(s, i, schedules):
        time = datetime.datetime.now() + datetime.timedelta(days=i)
        if i == 0:
            finish_time_range = (
                datetime.datetime.combine(datetime.date.today(), datetime.datetime.min.time()),
                datetime.datetime.combine(datetime.date.today(), datetime.datetime.max.time())
            )
            if len(models.FinishedSchedule.objects.filter(finish_time__range=finish_time_range, schedule_id=s.id)) != 0:
                return

        interval = time.date() - s.start_time.date()
        s.start_time += datetime.timedelta(days=interval.days)
        if s.start_time <= s.deadline:
            schedules.append(s)

    schedules = list(schedule_not_repeated)
    for i in range(search_day_num):
        time = datetime.datetime.now() + datetime.timedelta(days=i)
        for j in range(len(schedule_daily)):
            s = copy.copy(schedule_daily[j])
            update_time(s, i, schedules)
        for j in range(len(schedule_weekly)):
            s = copy.copy(schedule_weekly[j])
            if s.start_time.weekday() == time.weekday():
                update_time(s, i, schedules)
        for j in range(len(schedule_monthly)):
            s = copy.copy(schedule_monthly[j])
            if s.start_time.day == time.day:
                update_time(s, i, schedules)
    schedules.sort(key=lambda sc: sc.start_time)
    return schedules


@login_required
def home(request):
    user = request.user
    search_day_num = HOMEPAGE_SCHEDULE_DAY
    if request.method == 'POST':
        day_num = request.POST.get('search_day_num')
        finish_id = request.POST.get('finish_id')
        time_consumed = request.POST.get('time_consumed')
        if not (day_num is None):
            search_day_num = int(day_num)
        if not (finish_id is None):
            schedule = models.Schedule.objects.filter(id=finish_id)[0]
            if not schedule.is_repeated:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
                schedule.is_done = True
                schedule.save()
            elif not (time_consumed is None):
                if time_consumed != "":
                    models.FinishedSchedule.objects.create(schedule_id=finish_id, minutes_consumed=time_consumed)
                else:
                    models.FinishedSchedule.objects.create(schedule_id=finish_id)
            else:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)

    schedules = get_schedules(user, search_day_num)
    daily_schedules = get_schedules(user, 1)
    for ds in daily_schedules:
        if ds.is_repeated == True:
            ds.deadline = ds.start_time + datetime.timedelta(minutes=ds.expected_minutes_consumed)
    return render(request, "../templates/schedule/home.html",
                  {
                      'schedules': schedules,
                      'day_num': search_day_num,
                      'daily_schedules': daily_schedules
                  })


@login_required
def daily_schedules(request):
    user = request.user
    if request.method == 'POST':
        finish_id = request.POST.get('finish_id')
        time_consumed = request.POST.get('time_consumed')
        if not (finish_id is None):
            schedule = models.Schedule.objects.filter(id=finish_id)[0]
            if not schedule.is_repeated:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
                schedule.is_done = True
                schedule.save()
            elif not (time_consumed is None):
                models.FinishedSchedule.objects.create(schedule_id=finish_id, minutes_consumed=time_consumed)
            else:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
    schedules = get_schedules(user, 1)
    for s in schedules:
        if s.is_repeated:
            s.deadline = s.start_time + datetime.timedelta(minutes=s.expected_minutes_consumed)
    return render(request, "../templates/schedule/daily_schedules.html", {'schedules': schedules})

helper/views/settings.py
HOMEPAGE_SCHEDULE_DAY = 5

HOMEPAGE_BLOG_NUMBER = 20

BLOGPAGE_BLOG_NUMBER = 20

HOMEPAGE_COMMON_BLOG_DAY = 3

BLOGPAGE_COMMON_BLOG_DAY = 7

HOMEPAGE_HOT_BLOG_DAY = 7

BLOGPAGE_HOT_BLOG_DAY = 21

HOT_BLOG_PAGEVIEW = 50

helper/templates/group/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Group Home</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-text mx-3">Uni DAO</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                DAO项目
            </div>

            <!-- Nav Item - My DProject Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门DAO项目</span>
                </a>
            </li>

            <!-- Nav Item -  Hot DProject Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:dproject_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的DAO项目</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>Uni DAO</strong> 是一个任务驱动型的去中心化共创平台</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item">
                            <a class="nav-link" id="userName">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userId">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userEmail">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                            </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{{ group.group_name }}</h1>
                        <p>组长：{{ group.leader.username }}</p>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-9 mb-4">

                            <!-- Main Task -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">小组任务</h6>
                                </div>
                                <div class="card-body">
                                    {% if request.user.id == group.leader.id %}
                                        <p><a target="_blank" href="{% url 'helper:assign_add' group.belong_id group.id %}">新建任务</a></p>
                                    {% endif %}
                                    <ul>
                                        {% if assignments %}
                                            {% for a in assignments %}
                                                <li>{{ a.description }} {{ a.deadline }}</li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>

                            <!-- Sub Task -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">小组子任务</h6>
                                </div>
                                <div class="card-body">
                                    {% if request.user.id == group.leader.id %}
                                        <p><a target="_blank" href="{% url 'helper:sub_assign_add' group.belong_id group.id %}">新建子任务</a></p>
                                    {% endif %}
                                    <ul>
                                        {% if sub_assignments %}
                                            {% for a in sub_assignments %}
                                                <li>{{ a.description }} {{ a.deadline }} {{ a.user.username }}</li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>

                        </div>

                        <div class="col-lg-3 mb-4">

                            <!-- Friends List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">成员列表</h6>
                                </div>
                                <div class="card-body">
                                    {% if partcipants %}
                                        <ul>
                                        {% for p in partcipants %}
                                            <li><a target="_blank" href="{% url 'helper:public' p.user.id %}">
                                                {{ p.user.username }} {{ p.user.profile.name }}
                                            </a></li>
                                            {% if message %}
                                                <script>
                                                    mes="{{message}}";
                                                    if(!mes.match("message"))
                                                        alert(mes);
                                                </script>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Licensed Under MIT, Copyright &copy; Weibo LI 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>